apiVersion: 1

datasources:
  - name: OtelMind PostgreSQL
    type: postgres
    url: postgres:5432
    database: otelmind
    user: otelmind
    secureJsonData:
      password: otelmind
    jsonData:
      sslmode: disable
      maxOpenConns: 10
      connMaxLifetime: 14400
      postgresVersion: 1600
    isDefault: true
    editable: true
